'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ReferringHiddenFieldPropertyFromControlParameter


    ''' <summary>
    ''' _Default class.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated class.
    ''' </remarks>
    Partial Public Class _Default

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' spnMaxID control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected spnMaxID As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

        ''' <summary>
        ''' gvGridView control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected gvGridView As Global.DevExpress.Web.ASPxGridView.ASPxGridView

        ''' <summary>
        ''' hfData control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected hfData As Global.DevExpress.Web.ASPxHiddenField.ASPxHiddenField

        ''' <summary>
        ''' dsDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected dsDataSource As Global.System.Web.UI.WebControls.AccessDataSource
    End Class
End Namespace
